import Header from "../components/Header";
import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";
import type { Metadata } from 'next'
import { PrismaClient } from "@prisma/client";
export const metadata: Metadata = {
  title: 'Menu of Milestone-Grill | OpenTables ',
  description: 'Generated by create next app',
}

const prisma =new PrismaClient();
const fetchRestaurantMenu=async(slug:string)=>{
    const restaurant = await prisma.restaurant.findUnique({
        where:{
            slug
        },
        select:{
            items:true
        }
    })
    if(!restaurant) {
        throw new Error
    }
    return restaurant.items;
}
const RestaurantMenuPage=async({params}:{params:{slug:string}})=>{
  const menu = await fetchRestaurantMenu(params.slug);

    return(
  <>
 
      <div className="bg-white w-[100%] rounded p-3 shadow">
      <RestaurantNavBar slug={params.slug}/>
 
      <Menu menu={menu}/>
  
      </div>

    </>

    )
}
export default RestaurantMenuPage;