import Header from "../components/Header";
import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Menu of Milestone-Grill | OpenTables ',
  description: 'Generated by create next app',
}
const RestaurantMenuPage=()=>{
    return(
  <>
 
      <div className="bg-white w-[100%] rounded p-3 shadow">
      <RestaurantNavBar/>
 
      <Menu/>
  
      </div>

    </>

    )
}
export default RestaurantMenuPage;