import Header from "./components/Header";
import SearchSideBar from "./components/SearchSideBar";
import RestaurantCard from "./components/RestaurantCard";
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Search Restaurant | OpenTables ',
  description: 'Generated by create next app',
}
const SearchPage=()=>{
    return(
   <>
   <Header/>
    <div className="flex py-4 m-auto w-2/3 justify-between items-start">
      {/* SEARCH SIDE BAR */}
     <SearchSideBar/>
      {/* SEARCH SIDE BAR */}
      <div className="w-5/6">
        {/* RESAURANT CAR */}
       <RestaurantCard/>
        {/* RESAURANT CAR */}
      </div>
    </div>
    </>

    )
}
export default SearchPage;