import Header from "./components/Header";
import SearchSideBar from "./components/SearchSideBar";
import RestaurantCard from "./components/RestaurantCard";
import type { Metadata } from 'next'
import { PRICE, PrismaClient } from "@prisma/client";
export const metadata: Metadata = {
  title: 'Search Restaurant | OpenTables ',
  description: 'Generated by create next app',
}

const prisma = new PrismaClient();

interface SearchParams{
  city?:string,
  cuisine?:string,
  price?:PRICE
}

const searchRestaurantByCity=(searchParams:SearchParams)=>{
  const where: any={}
  if (searchParams.city){
    const location={
      name:{
        equals:searchParams.city.toLowerCase(),
      }
    }
    where.location=location;
  }
  if (searchParams.cuisine){
    const cuisine={
      name:{
        equals:searchParams.cuisine.toLowerCase(),
      }
    }
    where.cuisine=cuisine;
  }
  if (searchParams.price){
    const price={
      
        equals:searchParams.price,

    }
    where.price=price;
  }
  const select={
    id:true,
    name:true,
    main_image:true,
    price:true,
    cuisine:true,
    location:true,
    slug:true,
    reviews:true,

  }

  return prisma.restaurant.findMany({
    where,
    select,
  })

}

const fetchLocation =async()=>{
  return  prisma.location.findMany()
}
const fetchCuisine =async()=>{
  return  prisma.cuisine.findMany()
}

const SearchPage=async({searchParams}:{searchParams:SearchParams})=>{
  const restaurants = await searchRestaurantByCity(searchParams);
  const locations= await fetchLocation();
  const cuisines = await fetchCuisine();


    return(
   <>
   <Header/>
    <div className="flex py-4 m-auto w-2/3 justify-between items-start">
      {/* SEARCH SIDE BAR */}
     <SearchSideBar locations={locations} cuisines={cuisines} searchParams={searchParams}/>
      {/* SEARCH SIDE BAR */}
      <div className="w-5/6">
        {/* RESAURANT CAR */}
      
          {
            restaurants.length ?(
              restaurants.map((restaurant)=>{
                return <RestaurantCard restaurant={restaurant}/>
              })
              
            ):
            (
              <p>Sorry! The restaurant not available.</p>
            )
          }
        
        {/* RESAURANT CAR */}
      </div>
    </div>
    </>

    )
}
export default SearchPage;