
import Header from "./components/Header";
import Form from "./components/Form";
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Reserve at Milestone-Grill | OpenTables ',
  description: 'Generated by create next app',
}
const Reserve=()=>{
    return(
   
    <div className="border-t h-screen">
      <div className="py-9 w-3/5 m-auto">
        <Header/>
         {/* FORM */}
       <Form/>
      </div>
    </div>


    )
}
export default Reserve;